---
- name: Setup Apache, PHP, and MySQL with a working contact form and image
  hosts: webserver
  become: true

  vars:
    db_name: contact_db
    db_user: root                  # MySQL username (can be overridden)
    db_password: '123'             # MySQL password (vault in production!)
    allowed_host: '192.168.1.14'   # IP allowed to connect to DB
    krnetworkcloud_url: "https://krnetworkcloudnimanvihar.example.com"
    youtube_url: "https://www.youtube.com/channel/UCxxxxxxx"

  tasks:
    # ... your tasks before index.html deployment remain unchanged ...

    - name: Deploy contact form (index.html) with image included
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Contact Form</title>
            <meta charset="UTF-8">
          </head>
          <body>
            <h2>Enter Your Contact Info</h2>

            <!-- Show image -->
            <img src="images/cScreenshot_2025-09-14_160543.png" alt="Screenshot" style="max-width:600px; height:auto;"><br><br>

            <form action="submit.php" method="POST">
              <label for="name">Name:</label><br>
              <input type="text" id="name" name="name" required><br><br>
              <label for="phone">Phone:</label><br>
              <input type="text" id="phone" name="phone" required><br><br>
              <input type="submit" value="Submit">
            </form>

            <br>
            <a href="{{ krnetworkcloud_url }}">krnetwork cloud niman vihar</a><br>
            <a href="{{ youtube_url }}">Linux Wale Gure Ji YouTube Videos</a>
          </body>
          </html>
        owner: apache
        group: apache
        mode: '0644'

    - name: Deploy PHP backend (submit.php)
      copy:
        dest: /var/www/html/submit.php
        content: |
          <?php
          if ($_SERVER['REQUEST_METHOD'] === 'POST') {
              $name = htmlspecialchars(strip_tags(trim($_POST['name'] ?? '')));
              $phone = trim($_POST['phone'] ?? '');

              if (empty($name) || empty($phone)) {
                  die('Name and phone are required.');
              }
              if (!preg_match('/^[0-9]{10}$/', $phone)) {
                  die('Phone must be a 10-digit number.');
              }

              $conn = new mysqli("localhost", "{{ db_user }}", "{{ db_password }}", "{{ db_name }}");
              if ($conn->connect_error) {
                  die('Connection failed: ' . htmlspecialchars($conn->connect_error));
              }

              $stmt = $conn->prepare("INSERT INTO contacts (name, phone) VALUES (?, ?)");
              if (!$stmt) {
                  die('Prepare failed: ' . htmlspecialchars($conn->error));
              }
              $stmt->bind_param('ss', $name, $phone);

              if ($stmt->execute()) {
                  echo 'Thank you! Your info has been recorded.';
              } else {
                  echo 'Error saving data: ' . htmlspecialchars($stmt->error);
              }

              $stmt->close();
              $conn->close();
          } else {
              echo 'Invalid request method.';
          }
          ?>
        owner: apache
        group: apache
        mode: '0644'

    # ... rest of your playbook remains unchanged ...
