---
- name: Setup Apache, PHP, and MySQL with a working contact form and image
  hosts: webserver
  become: true

  vars:
    db_name: contact_db
    db_user: root                  # MySQL username (can be overridden)
    db_password: '123'             # MySQL password (vault in production!)
    allowed_host: '192.168.1.14'   # IP allowed to connect to DB
    krnetworkcloud_url: "https://krnetworkcloud.org/?srsltid=AfmBOopc_aoC7okycWr10-cdu3zZGJKH5SkzGMbVzQ6D9rLvXPbhjjWO"
    youtube_url: "https://www.youtube.com/channel/UCxxxxxxx"

  tasks:
    # Your previous tasks remain the same...

    - name: Deploy contact form (index.html) with image included
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Contact Form</title>
            <meta charset="UTF-8">
          </head>
          <body>
            <h2>Enter Your Contact Info</h2>

            <!-- Show image -->
            <img src="images/cScreenshot_2025-09-14_160543.png" alt="Screenshot" style="max-width:600px; height:auto;"><br><br>

            <form action="submit.php" method="POST">
              <label for="name">Name:</label><br>
              <input type="text" id="name" name="name" required><br><br>
              <label for="phone">Phone:</label><br>
              <input type="text" id="phone" name="phone" required><br><br>
              <input type="submit" value="Submit">
            </form>

            <br>
            <a href="{{ krnetworkcloud_url }}">krnetwork cloud niman vihar</a><br>
            <a href="{{ youtube_url }}">Linux Wale Gure Ji YouTube Videos</a>
          </body>
          </html>
        owner: apache
        group: apache
        mode: '0644'

    # Continue rest of your playbook...
