---
- name: Setup Apache Web Server on 192.168.1.28
  hosts: all
  become: true

  tasks:
    - name: Check if YUM is available
      command: which yum
      register: yum_check
      failed_when: yum_check.rc != 0

    - name: Install Apache (httpd) if not already present
      yum:
        name: httpd
        state: present

    - name: Ensure httpd service is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy HTML file to index.html
      copy:
        src: html-code
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Copy video file to web server
      copy:
        src: 115534-704906218_medium.mp4
        dest: /var/www/html/115534-704906218_medium.mp4
        owner: root
        group: root
        mode: '0644'

    - name: Restart Apache to apply changes
      service:
        name: httpd
        state: restarted

    - name: Confirm Apache is enabled
      command: systemctl is-enabled httpd
      register: enabled_status
      changed_when: false

    - name: Confirm Apache is running
      command: systemctl is-active httpd
      register: active_status
      changed_when: false

    - name: Show final Apache status
      debug:
        msg: |
          ✅ Apache Status on 192.168.1.28
          - Enabled at boot: {{ enabled_status.stdout }}
          - Currently running: {{ active_status.stdout }}
          - Access site via: http://192.168.1.28
          - Access video via: http://192.168.1.28/115534-704906218_medium.mp4
