---
- name: Setup Apache, PHP, and MySQL with a working contact form and image
  hosts: webserver
  become: true

  vars:
    db_name: contact_db
    db_user: root
    db_password: '123'  # Change to secure password in production
    allowed_host: '192.168.1.14'  # IP allowed to connect to DB

  tasks:

    - name: Install Apache, PHP, and MariaDB
      yum:
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Set MySQL root password and secure installation (simulate mysql_secure_installation)
      community.mysql.mysql_user:
        name: root
        host_all: true
        password: "{{ db_password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Grant remote privileges to root from allowed host
      community.mysql.mysql_user:
        name: root
        host: "{{ allowed_host }}"
        password: "{{ db_password }}"
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "{{ db_password }}"

    - name: Create MySQL database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ db_password }}"

    - name: Create table 'contacts' in database
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db_password }}"
        query: |
          CREATE TABLE IF NOT EXISTS {{ db_name }}.contacts (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(100),
            phone VARCHAR(15)
          );

    - name: Create images directory in web root
      file:
        path: /var/www/html/images
        state: directory
        owner: apache
        group: apache
        mode: '0755'

    - name: Copy screenshot image to web directory
      copy:
        src: "cScreenshot 2025-09-14 160543.png"
        dest: /var/www/html/images/cScreenshot_2025-09-14_160543.png
        owner: apache
        group: apache
        mode: '0644'

    - name: Deploy contact form (index.html) with image included
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Contact Form</title>
            <meta charset="UTF-8">
          </head>
          <body>
            <h2>Enter Your Contact Info</h2>

            <!-- Show image -->
            <img src="images/cScreenshot_2025-09-14_160543.png" alt="Screenshot" style="max-width:600px; height:auto;"><br><br>

            <form action="submit.php" method="POST">
              <label for="name">Name:</label><br>
              <input type="text" id="name" name="name" required><br><br>
              <label for="phone">Phone:</label><br>
              <input type="text" id="phone" name="phone" required><br><br>
              <input type="submit" value="Submit">
            </form>

            <br>
            <a href="https://krnetworkcloudnimanvihar.example.com">krnetwork cloud niman vihar</a><br>
            <a href="https://www.youtube.com/channel/UCxxxxxxx">Linux Wale Gure Ji YouTube Videos</a>
          </body>
          </html>
        owner: apache
        group: apache
        mode: '0644'

    - name: Deploy PHP backend (submit.php)
      copy:
        dest: /var/www/html/submit.php
        content: |
          <?php
          if ($_SERVER['REQUEST_METHOD'] === 'POST') {
              $name = htmlspecialchars(strip_tags(trim($_POST['name'] ?? '')));
              $phone = trim($_POST['phone'] ?? '');

              if (empty($name) || empty($phone)) {
                  die('Name and phone are required.');
              }
              if (!preg_match('/^[0-9]{10}$/', $phone)) {
                  die('Phone must be a 10-digit number.');
              }

              $conn = new mysqli("localhost", "{{ db_user }}", "{{ db_password }}", "{{ db_name }}");
              if ($conn->connect_error) {
                  die('Connection failed: ' . htmlspecialchars($conn->connect_error));
              }

              $stmt = $conn->prepare("INSERT INTO contacts (name, phone) VALUES (?, ?)");
              if (!$stmt) {
                  die('Prepare failed: ' . htmlspecialchars($conn->error));
              }
              $stmt->bind_param('ss', $name, $phone);

              if ($stmt->execute()) {
                  echo 'Thank you! Your info has been recorded.';
              } else {
                  echo 'Error saving data: ' . htmlspecialchars($stmt->error);
              }

              $stmt->close();
              $conn->close();
          } else {
              echo 'Invalid request method.';
          }
          ?>
        owner: apache
        group: apache
        mode: '0644'

    - name: Restart Apache to apply changes
      service:
        name: httpd
        state: restarted

    - name: Show final status
      debug:
        msg: |
          ✅ Apache + MySQL + PHP Contact Form with image deployed!
          🌐 Visit: http://192.168.1.100/
          📬 Data stored in MySQL → contact_db.contacts
